// ============================================
// Central Dimension Table
// ============================================

Table dim_dates {
  date_id integer [pk, increment]
  full_date date // 2026-02-06, 2027-03-09, 2028-04-10 
  year integer // 2026, 2027, 2028
  quarter char(2) // Q1, Q2, Q3
  month integer // 2, 3, 4
  month_name varchar(20) // February, March, April
  week_number integer // 16, 17, 18
  day_name varchar(20) // Monday, Tuesday, Wednesday
  is_weekend boolean // FALSE, FALSE, FALSE
  is_holiday boolean // FALSE, FALSE, FALSE
  created_at datetime [default: `now()`] // 2026-02-06 15:58:00, 2026-02-06 17:58:00, 2026-02-06 19:58:00
}





// ============================================
// Indicator: Reduction percentage in inflation rates through price monitoring and direct selling of basic commodities
// Lead Department: OPPDC
// Frequency: Annually
// How to verify the data?: Go to Provincial Online Price Monitoring System
// ============================================

Table dim_local_government_units {
  lgu_id integer [pk, increment]
  district_name varchar(50) // District 1, District 2, District 1
  lgu_name varchar(150) // Abucay, Balanga, Orani
  created_at datetime [default: `now()`] // 2026-02-06 15:58:00, 2026-02-06 17:58:00, 2026-02-06 19:58:00
}

Table dim_agricultural_products {
  product_id integer [pk, increment]
  commodity_type varchar(255) // IMPORTED COMMERCIAL RICE, FISH (per kg), HIGHLAND VEGETABLES (per kg)
  product_name varchar(255) // Special (Blue tag), Galunggong (Local), Pechay (Baguio)
  created_at datetime [default: `now()`] // 2026-02-06 16:13:13, // 2026-02-06 20:13:13, // 2026-02-07 16:13:13
}

Table dim_helpers {
  helper_id integer [pk, increment]
  helper varchar(20) // CURRENT, PREVIOUS, OTHER
  created_at datetime [default: 'now()'] // 2026-02-06 16:13:13, // 2026-02-06 20:13:13, // 2026-02-07 16:13:13 
}

Table fact_prices {
  price_id integer [pk, increment]
  lgu_id integer [ref: > dim_local_government_units.lgu_id]
  product_id integer [ref: > dim_agricultural_products.product_id]
  observation_date_id integer [ref: > dim_dates.date_id]
  coverage_start_date_id integer [ref: > dim_dates.date_id]
  coverage_end_date_id integer [ref: > dim_dates.date_id]
  helper_id integer [ref: > dim_helpers.helper_id]
  average_price decimal(10, 2) // 216.00, 172.50, 216
  prevailing_price decimal(10, 2) // 225.00, 170.00, 220
  created_at timestamp [default: `now()`] // 2026-02-06 16:13:13, // 2026-02-06 20:13:13, // 2026-02-07 16:13:13 
  updated_at timestamp // 2026-02-06 16:13:13, // 2026-02-06 20:13:13, // 2026-02-07 16:13:13

  indexes {
    (observation_date_id, lgu_id, product_id) [name: 'idx_price_lookup']
    (coverage_start_date_id, coverage_end_date_id) [name: 'idx_coverage_period']
  }
}



// ============================================
// Indicator: Increase percentage in barangays with completed Barangay Master Development Plans
// Lead Department: OPPDC
// Frequency: Annually
// How to verify the data?: Submitted reports of District Offices about the number of barangays who completed their master development plan per municipalities divided by the number of barangays per municipalities
// ============================================

Table dim_districts {
  district_id integer [pk, increment]
  district_name varchar(100) // District 1, District 2, District 3
  created_at datetime [default: 'now()'] // 2026-02-06 16:18:18, 2026-02-06 17:18:18, 2026-02-06 20:18:18
}

Table dim_municipalities {
  municipality_id integer [pk, increment]
  district_id integer [ref: > dim_districts.district_id]
  municipality_name varchar(100) // Hermosa, City of Balanga, Bagac
  created_at datetime [default: `now()`] // 2026-02-06 16:18:18, 2026-02-06 17:18:18, 2026-02-06 20:18:18
}

Table fact_barangay_development_plans {
  plan_id integer [pk, increment]
  municipality_id integer [ref: > dim_municipalities.municipality_id]
  observation_date_id integer [ref: > dim_dates.date_id]
  coverage_start_date_id integer [ref: > dim_dates.date_id]
  coverage_end_date_id integer [ref: > dim_dates.date_id]
  barangays_with_completed_plans integer // 13, 21, 10
  total_barangays integer // 23, 25, 14
  completion_percentage decimal(5, 2) // 56.52, 84.00, 71.49
  created_at datetime [default: `now()`] // 2026-02-06 16:18:18, 2026-02-06 17:18:18, 2026-02-06 20:18:18
  updated_at datetime // 2026-02-06 16:18:18, 2026-02-06 17:18:18, 2026-02-06 20:18:18
  indexes {
    (municipality_id, observation_date_id) [name: 'idx_plan_lookup']
    (coverage_start_date_id, coverage_end_date_id) [name: 'idx_coverage_lookup']
  }
}





// ============================================
// Indicator: Increase percentage in citizen concerns addressed via the 8888 hotline
// Lead Department: PHRMO
// Frequency: Annually
// How to verify the data?: Submitted Performance Report transmitted by the 8888 Citizen's Complaint Center to the PGO
// ============================================

Table dim_ticket_classifications {
  classification_id integer [pk, increment]
  classification_name varchar(255) // 2025 Graft and Corruption, 2025 Integrity and Conduct, 2025 Frontline Service Procedures
  created_at datetime [default: `now()`] // 2026-02-07 16:41:23, 2026-02-07 16:41:33, 2026-02-07 16:41:43
}

Table dim_ticket_names {
  ticket_name_id integer [pk, increment]
  classification_id integer [ref: > dim_ticket_classifications.classification_id]
  ticket_name varchar(255) // 2025 Against Government Official, 2025 - Integrity and Conduct - Official, 2025 - Discourtesy
  created_at datetime [default: `now()`] // 2026-02-07 19:23:59, 2026-02-07 21:23:59, 2026-02-07 12:23:59
}

Table dim_times {
  time_id integer [pk, increment]
  time_value time [unique] // 12:04:33
  period varchar(2) // AM/PM
  time_label varchar(20) // Morning, Afternoon, Evening
  created_at datetime [default: 'now()'] // 2026-02-07 19:23:59, 2026-02-07 21:23:59, 2026-02-07 12:23:59
}

Table fact_performance_reports {
  report_id integer [pk, increment]
  ticket_name_id integer [ref: > dim_ticket_names.ticket_name_id]
  report_date_id integer [ref: > dim_dates.date_id]
  coverage_start_date_id integer [ref: > dim_dates.date_id]
  coverage_end_date_id integer [ref: > dim_dates.date_id]
  report_time_id integer [ref: > dim_times.time_id]
  tickets_resolved_count integer // 23, 24, 25
  tickets_in_progress_count integer // 0, 1, 2
  tickets_pending_count integer // 3, 2, 1
  total_tickets integer // 26, 26, 28
  resolution_rate decimal(5, 2) // 88.46, 92.30, 88.29
  created_at datetime [default: `now()`] // 2026-02-07 19:23:59, 2026-02-07 21:23:59, 2026-02-07 12:23:59
  updated_at datetime // 2026-02-07 19:23:59, 2026-02-07 21:23:59, 2026-02-07 12:23:59

  indexes {
    (report_date_id, ticket_name_id) [name: 'idx_report_lookup']
    (coverage_start_date_id, coverage_end_date_id) [name: 'idx_coverage_lookup']
  }
}



// ============================================
// Indicator: Improvement percentage in government employee service quality
// Lead Department: PHRMO
// Frequency: Annually
// How to verify the data?: Information Table for the Outreach Program provided by the PHRMO
// ============================================

Table beneficiaries {
  beneficiary_id integer [pk, increment]
  beneficiary varchar(255) // Aeta Magbukun,  Children of SOS Orphanage, Staff of Bahay Puso
  created_at datetime // 2026-02-07 18:03:03, 2026-02-07 19:03:03, 2026-02-07 20:03:03
  updated_at datetime // 2026-02-07 18:03:03, 2026-02-07 19:03:03, 2026-02-07 20:03:03
}

Table implementing_departments {
  department_id integer [pk, increment]
  department_name varchar(150) // Provincial Information Office, Office of the Provincial Planning and Development Coordinator, Bataan Public-Private Partnership Investment Center
  department_code varchar(25) // PIO, OPPDC, BPPPIC
  created_at datetime // 2026-02-07 18:03:03, 2026-02-07 19:03:03, 2026-02-07 20:03:03
  updated_at datetime // 2026-02-07 18:03:03, 2026-02-07 19:03:03, 2026-02-07 20:03:03
}

Table program_heads {
  program_head_id integer [pk, increment]
  department_id integer [ref: > implementing_departments.department_id ]
  program_head varchar(100) // Ms. Angel O.L Lara, Ar. Mc Jefferson M. Valerio, Mr. Abul Khayr Amalon M. Alonto I
  created_at datetime [default: 'now()'] // 2026-02-07 19:24:24, 2026-02-07 19:54:24, 2026-02-07 20:24:24 
  updated_at datetime // 2026-02-07 19:24:24, 2026-02-07 19:54:24, 2026-02-07 20:24:24
}

Table locations {
  location_id integer [pk, increment]
  location varchar(100) // Limay, Mariveles, Various parts of Bataan
  created_at datetime [default: 'now()'] // 2026-02-07 19:49:44, 2026-02-08 19:49:44, 2026-02-09 19:49:44
}