enum day_of_week {
  Monday
  Tuesday
  Wednesday
  Thursday
  Friday
  Saturday
  Sunday
}

enum helper {
  Previous
  Current
  Other
}

enum crime_category {
  IndexCrime
  OtherCrimeSlashIndex
}

enum accident_type {
  Vehicular
  Fire
  Medical
}

enum accident_severity {
  Minor
  Major
  Fatal
}

enum calamity_type {
  NaturalCalamities
  HydrologicalCalamities
  GeologicalCalamities
  BiologicalCalamities
  ManMadeCalamities
}

/*
Table sectors {
  sector_id integer [pk, increment]
  sector varchar(255) // Development Administration, Economic, Social
  dimension varchar(255) // Governance, Standard of Living
}
*/





// Department who will use this data: OPPDC
// Indicator: Percentage of reduction in inflation rates through price monitoring and direct selling of basic commodities
// Frequency: Annually
// Data Source: OPPDC - Development Research and Statistics Division Spreadsheet
// How to verify this data for the integrity: Check the Provincial Price Monitoring System of Development Research and Statistics Divsion from OPPDC for comparison

Table local_government_units {
  local_government_unit_id integer [pk, increment]
  local_government_unit varchar(50) // Abucay, Balanga, etc.
  district_number integer // 1, 2, 3, etc.
}

Table commodity_types {
  commodity_type_id integer [pk, increment]
  commodity_type varchar(255) // IMPORTED COMMERCIAL RICE (per kg), HIGHLAND VEGETABLES (per kg)
}

Table agricultural_products {
  agricultural_product_id integer [pk, increment] 
  commodity_type_id integer [ref: > commodity_types.commodity_type_id]
  agricultural_product varchar(255) // Cooking oil (Palm) 1L, NFA (Wellmilled)
}

Table dates {
  date_id integer [pk, increment]
  full_date date // // YYYY/MM/DD
  year year // 2025
  quarter integer // 3
  month integer // 3
  week_number integer // 54
  day_of_week day_of_week // Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, and Sunday
}

Table helpers {
  helper_id integer [pk, increment]
  helper helper // Previous, Current, Other
}

Table prices {
  price_id integer [pk, increment]
  local_government_unit_id integer [ref: > local_government_units.local_government_unit_id]
  agricultural_product_id integer [ref: > agricultural_products.agricultural_product_id]
  observation_datetime_id integer [ref: > dates.date_id]
  coverage_period_start_date integer [ref: > dates.date_id]
  coverage_period_end_date integer [ref: > dates.date_id]
  helper_id integer [ref: > helpers.helper_id]
  currency varchar(25) // PHP
  average_price decimal(11, 2) // 53.50
  prevailing_price decimal(11, 2) // 53.50
}





// Department who will use this data: Legal & PHRMO
// Indicator: % increase in citizen concerns addressed via the 8888 hotline
// Frequency: Annually
// Data Source: Annual Performance Report of 8888 Citizens' Complaint Center (8888 CCC) from Legal & PHRMO Office
// How to verify this data for the integrity: Check the Performance report for a certain period of month sent by 8888 Citizens' Complaint Center (8888 CCC)

Table ticket_classifications {
  ticket_classification_id integer [pk, increment]
  ticket_classification varchar(255) // 2024 Graft and Corruption, 2024 LGU Concerns
}

Table ticket_names {
  ticket_name_id integer [pk, increment]
  ticket_classification_id integer [ref: > ticket_classifications.ticket_classification_id]
  ticket_name varchar(255) // 2024 Against Government Official, 2024 - Agains Government Employee
}

Table ticket_summaries {
  ticket_summary_id integer [pk, increment]
  dates_id integer [ref: > dates.date_id]
  ticket_name_id integer [ref: > ticket_names.ticket_name_id]
  acted_upon bigint // 3
  under_processing bigint // 2
  unacted bigint // 4
  total_ticket bigint // 9
}





// Department who will use this data: MBDA/PDRRMO
// Indicator: % reduction in crime rates through collaboration with law enforcement
// Frequency: Annually
// Data Source: PNP Crime Reports from PNP
// How to verify this data for the integrity: Cross-check the data given by the PNP to the OPPDC - Development Research and Statistics Division

Table police_stations {
  police_station_id integer [pk, increment]
  police_station varchar(255) // Balanga City Police Station 1
  barangay varchar(255) // San Jose, Munting Batangas, Tuyo
}

Table crime_datetimes {
  crime_datetime_id integer [pk, increment]
  date_commited_id integer [ref: > dates.date_id]
  time_commited time // 13:00
}

Table crime_categories {
  crime_category_id integer [pk, increment]
  crime_category crime_category // Index Crime, Other Crime/Index
}

Table stages_of_felony {
  stage_of_felony_id integer [pk, increment]
  stage_of_felony varchar(100) // Consummated, etc.
}

Table crime_offenses {
  crime_offense_id integer [pk, increment]
  crime_category_id integer [ref: > crime_categories.crime_category_id]
  stage_of_felony_id integer [ref: > stages_of_felony.stage_of_felony_id]
  crime_offense varchar(100) // Adultery, Rape, Murder
}

Table crime_incidents {
  crime_incident_id integer [pk, increment]
  police_station_id integer [ref: > police_stations.police_station_id]
  crime_datetime_id integer [ref: > crime_datetimes.crime_datetime_id]
  crime_offense_id integer [ref: > crime_offenses.crime_offense_id]
  modus varchar(255) // Caught in motel, etc.
}





// Department who will use this data: PDRRM (Place of occurence: ), MBDA (Place of occurence: Latitude/Longitude), PNP (Place of Occurence: Barangay)
// Indicator: % reductions on accidents (place of occurrence)
// Frequency: Monthly
// Data Source:
// How to verify this data for the integrity:

Table accident_types {
  accident_type_id integer [pk, increment]
  accident_type accident_type // Vehicular, Fire, Medical
}

Table accident_severities {
  accident_severity_id integer [pk, increment]
  accident_severity accident_severity // Minor, Major, Fatal
}

Table accidents {
  accident_id integer [pk, increment]
  accident_date_id integer [ref: > dates.date_id]
  accident_types integer [ref: > accident_types.accident_type_id]
  accident_severity_id integer [ref: > accident_severities.accident_severity_id]
  city_municipality varchar(100) // Balanga City, Abucay, Orani
  barangay varchar(100) // San Jose, Bagong Silang
  latitude decimal(10, 8) // 14.681234
  longitude decimal(10, 8) // 120.534567
}


// Department who will use this data: PDRRM, MBDA
// Indicator: % reduction of injury among affected population during calamity
// Frequency: During SitRep
// How to verify this data for the integrity:

Table calamities {
  calamity_id integer [pk, increment]
  // reference to date using calamity_date_id
  calamity varchar(255) // Severe Tropical Storm Paeng 2024, 5.9 Magnitude Earthquake
  calamity_type calamity_type // Natural Calamities, Hydrological Calamities
  calamity_subtype varchar(150) // Tropical Cyclone, Floods, etc.
}

Table barangays {
  barangay_id integer [pk, increment]
  barangay varchar(100) // San Jose, Mabatang
  barangay_population bigint
  city_municipality varchar(100) // Balanga City, Orion
}

Table injury_types {
  injury_type_id integer [pk, increment]
  
}
Table injuries {
  injury_id integer [pk, increment]
  // Reference to injuries table
}