Table dim_dates {
  date_id INTEGER PK
  full_date DATE
  year YEAR
  quarter CHAR(2)
  month INTEGER
  month_name VARCHAR(20)
  week_number INTEGER
  day INTEGER
  day_of_week VARCHAR(20)
}

Table dim_barangays {
  barangay_id INTEGER PK
  barangay_name VARCHAR(100)
  city VARCHAR(50)
  province_name VARCHAR(50)
  postal_code INT(4)
  region_name VARCHAR(80)
  classification CHAR(5)
}


Table dim_development_plans {
  plan_id INTEGER PK
  development_plan_title VARCHAR(255)
  development_plan_description TEXT
  inclusive_plan_year VARCHAR(50)
  status VARCHAR(20)
  date_started DATE
  date_approved DATE
  date_completed DATE
}

Table dim_status {
  status_id INTEGER PK
  status VARCHAR(25)
  is_active BOOLEAN
  is_completed BOOLEAN
}

Table fact_plan_completions {
  id INTEGER PK
  date_id INTEGER [ref: > dim_dates.date_id]
  barangay_id INTEGER [ref: > dim_barangays.barangay_id]
  plan_id INTEGER [ref: > dim_development_plans.plan_id]
  status_id INTEGER [ref: > dim_status.status_id]
}

Table barangays {
  barangay_id integer [pk, increment]
  barangay_name varchar(100)
  municipality varchar(100)
  province varchar(100)
  region varchar(100)
  population bigint
  classification varchar(20)
  is_active boolean
}

enum status {
  None
  Draft
  Approved
  Completed
  Implementation
}

enum source {
  LGU
  National
  NGO
  Provate
  Mixed
}

Table master_development_plans {
  plan_id integer [pk, increment]
  barangay_id integer [ref: > barangays.barangay_id]
  plan_period varchar(60)
  current_status status
  date_started date
  date_approved date
  date_completed date
  funding_source source
  budget decimal(15, 2)
  remarks text
  created_by varchar(255)
  created_date date
}

Table plan_progress {
  progress_id integer [pk, increment]
  plan_id integer [ref: > master_development_plans.plan_id]
  progress_date date
  status varchar(50)
  completion_percentage decimal (4, 1)
  remarks text
  reported_by varchar(100)
  reported_datetime datetime
}