// Department whol will use this data: OPPDC
// Indicator: Percentage of reduction in inflation rates through price monitoring and direct selling of basic commodities

Table local_government_units {
  local_government_unit_id integer [pk, increment]
  local_government_unit varchar(50) // Abucay, Balanga, etc.
  district_number integer // 1, 2, 3, etc.
}

Table commodity_types {
  commodity_type_id integer [pk, increment]
  commodity_type varchar(255) // IMPORTED COMMERCIAL RICE (per kg), HIGHLAND VEGETABLES (per kg)
}

Table agricultural_products {
  agricultural_product_id integer [pk, increment] 
  commodity_type_id integer [ref: > commodity_types.commodity_type_id]
  agricultural_product varchar(255) // Cooking oil (Palm) 1L, NFA (Wellmilled)
}

Table dates {
  date_id integer [pk, increment]
  full_date date // 1/4/2026
  year year // 2025
  month integer // 3
  week_number integer // 54
}

// Create helper table

Table prices {
  price_id integer [pk, increment]
  local_government_unit_id integer [ref: > local_government_units.local_government_unit_id]
  agricultural_product_id integer [ref: > agricultural_products.agricultural_product_id]
  observation_date_id integer [ref: > dates.date_id]
  coverage_period_start_date integer [ref: > dates.date_id]
  coverage_period_end_date integer [ref: > dates.date_id]
  currency varchar(25) // PHP
  average_price decimal(11, 2) // 53.50
  prevailing_price decimal(11, 2) // 53.50
}